import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Sidebar from "../components/menu/sidebar";
import TopMenu from "../components/menu/topmenu";
import AuthWrapper from "../components/auth/AuthWrapper";
import StudentSidebar from "../components/menu/studentSidebar";
import StudentTopmenu from "../components/menu/studentTopmenu";
import Providers from "../providers/providers";
import GlobalSpinner from "@/components/GlobalSpinner";
import GlobalErrorHandler from "@/lib/GlobalErrorHandler";
import MyToaster from "../components/general/Toast/MyToaster";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Sqooli",
  description: "Generated by Swiftcode",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex h-screen bg-gray-100 relative">
          {/* Toggle button - always visible, positioned independently */}
          <StudentSidebar />
          <MyToaster/>
<GlobalErrorHandler />
          {/* Main Content */}
          <div className="flex-1 flex flex-col overflow-hidden">
            {/* Header */}
            <StudentTopmenu />

            {/* Page Content */}
            <main className="flex-1 overflow-auto bg-white relative h-screen">
              <Providers>
                 <GlobalSpinner/>
                <AuthWrapper>{children}</AuthWrapper>
              </Providers>
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
