import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";

import AuthWrapper from "../components/auth/AuthWrapper";
import Providers from "../providers/providers";
import GlobalSpinner from "@/components/GlobalSpinner";
import AdminSidebar from "../components/menu/adminSideMenu";
import AdminTopmenu from "../components/menu/adminTopMenu";
import MyToaster from "../components/general/Toast/MyToaster";
import GlobalErrorHandler from "@/lib/GlobalErrorHandler";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Sqooli",
  description: "Generated by Swiftcode",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex h-screen bg-white relative">
          {/* Toggle button - always visible, positioned independently */}
          <AdminSidebar />
<MyToaster/>
 <GlobalErrorHandler />
          {/* Main Content */}
          <div className="flex-1 flex flex-col overflow-hidden">
            {/* Header */}
            <AdminTopmenu />

            {/* Page Content */}
            <main className="flex-1 overflow-auto bg-white relative h-screen">
              <Providers>
                 <GlobalSpinner/>
                <AuthWrapper>{children}</AuthWrapper>
              </Providers>
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
