/* eslint-disable no-irregular-whitespace */
import { ChevronDown, ChevronRight, Download, EllipsisVertical, Filter, Flame, Grid2x2, List, Search, Users, X } from 'lucide-react'
import { useState } from 'react'
import TeacherDashboardLayout from './TeacherDashboardLayout'
import teacherAvatar from '../../assets/images/whats-popular/teacher.webp'
import speaker from '../../assets/images/student-flow/speaker.svg'
import '../../styles/pages/teacher-students.css'

type Student = { id: number; name: string; email: string; performance: string; attendance: string; inactive?: boolean }
const students: Student[] = [
    { id: 1, name: 'Olivia Rhye', email: 'oliviaryhe@gmail.com', performance: '50', attendance: '50' },
    { id: 2, name: 'Phoenix Baker', email: 'phoenixbaker@gmail.com', performance: '50', attendance: '50' },
    { id: 3, name: 'Lana Steiner', email: 'lanasteiner@gmail.com', performance: '50', attendance: '50' },
    { id: 4, name: 'Demi Wilkinson', email: 'demiwilkinson@gmail.com', performance: '50', attendance: '50' },
    { id: 5, name: 'Candice Wu', email: 'candicewu@gmail.com', performance: '50', attendance: '50' },
    { id: 6, name: 'Natali Craig', email: 'natalicraig@gmail.com', performance: '50', attendance: '50' },
    { id: 7, name: 'Drew Cano', email: 'drewcano@gmail.com', performance: '50', attendance: '50' },
    { id: 8, name: 'Orlando Diggs', email: 'orlandodiggs@gmail.com', performance: '50', attendance: '50' },
    { id: 9, name: 'Andi Lane', email: 'andilane@gmail.com', performance: '50', attendance: '50' },
    { id: 10, name: 'Kate Morrison', email: 'katemorrison@gmail.com', performance: '50', attendance: '50' },
]

export default function TeacherStudentsPage() {
    const [query, setQuery] = useState('')
    const [view, setView] = useState<'grid' | 'list'>('grid')
    const [selected, setSelected] = useState<Student | null>(null)
    const visible = students.filter(student => `${student.name} ${student.email}`.toLowerCase().includes(query.toLowerCase()))
    return <TeacherDashboardLayout activePath="/teacher/students">
        <section className="teacher-students-page" aria-labelledby="teacher-students-title">
            <div className="teacher-students-page__layout"><AccountRail /><div className="teacher-students-page__content">
                <header className="teacher-students-page__header"><div><h1 id="teacher-students-title">Students</h1><p>Manage students performance</p></div></header>
                <div className="teacher-students-page__toolbar"><label><Search size={19} /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search" aria-label="Search students" /><Filter size={18} /></label><div className="teacher-students-page__view-toggle"><button className={view === 'grid' ? 'is-active' : ''} type="button" onClick={() => setView('grid')}><Grid2x2 size={15} /> Grid</button><button className={view === 'list' ? 'is-active' : ''} type="button" onClick={() => setView('list')}><List size={15} /> List</button></div></div>
                {view === 'grid' ? <div className="teacher-students-page__grid">{visible.map(student => <StudentCard key={student.id} student={student} onView={() => setSelected(student)} />)}</div> : <StudentList rows={visible} onView={student => setSelected(student)} />}
                {visible.length === 0 && <p className="teacher-students-page__empty">No students match your search.</p>}<Pagination />
            </div></div>
        </section>{selected && <StudentProfileModal student={selected} onClose={() => setSelected(null)} />}
    </TeacherDashboardLayout>
}

function AccountRail() { return <aside className="teacher-students-page__account"><div className="teacher-students-page__school-mark"><Users size={27} /></div><h2>Mathematic Excellence<br />Academy</h2><span className="teacher-students-page__school-tag">Online School</span><p>Contact Information</p><strong>+254712 345 678</strong><strong>mathematicexcel@gmail.com</strong><button type="button">Switch Account</button><div className="teacher-students-page__referral"><img src={speaker} alt="" /><div><b>Refer &amp; Earn with Sqooli</b><small>Share your unique link to students &amp; parents to join Sqooli</small><button type="button">Copy Link</button></div></div></aside> }
function StudentCard({ student, onView }: { student: Student; onView: () => void }) { return <article className="teacher-student-card"><header><div><h2>Jane Doe</h2><p>johndoe@gmail.com</p></div><button type="button" aria-label={`More actions for ${student.name}`}><EllipsisVertical size={20} /></button></header><img src={teacherAvatar} alt="Student profile" /><div className="teacher-student-card__metrics"><span><small>Performance Rate</small><strong>{student.performance}%</strong></span><span><small>Attendance Rate</small><strong>{student.attendance}%</strong></span></div><button className="teacher-student-card__view" type="button" onClick={onView}>View</button></article> }
function StudentList({ rows, onView }: { rows: Student[]; onView: (student: Student) => void }) { return <div className="teacher-students-page__list-wrap"><table><thead><tr><th>Name</th><th>Performance Rate (%)</th><th>Attendance Rate (%)</th><th /></tr></thead><tbody>{rows.map(student => <tr key={student.id}><td data-label="Name"><span className="teacher-student-list__person"><i>{student.name[0]}</i><span><b>{student.name}</b><small>{student.email}</small></span></span></td><td data-label="Performance Rate (%)">{student.performance}</td><td data-label="Attendance Rate (%)">{student.attendance}</td><td><button type="button" onClick={() => onView(student)}>View</button></td></tr>)}</tbody></table></div> }
function Pagination() { return <footer className="teacher-students-page__pagination"><span>Page <b>1</b> of 10</span><div><button type="button" disabled>Previous</button><button type="button">Next</button></div></footer> }

function StudentProfileModal({ student, onClose }: { student: Student; onClose: () => void }) {
    const [tab, setTab] = useState<'overview' | 'lessons' | 'reports'>('overview')
    return <div className="teacher-student-profile__backdrop" onMouseDown={event => event.target === event.currentTarget && onClose()}><section className="teacher-student-profile" role="dialog" aria-modal="true" aria-labelledby="student-profile-title"><header className="teacher-student-profile__topbar"><div><Users size={16} /> Students <ChevronRight size={15} /><b>{student.name}</b></div><button type="button" aria-label="Close student profile" onClick={onClose}><X size={20} /></button></header><div className="teacher-student-profile__layout"><aside className="teacher-student-profile__sidebar"><div className="teacher-student-profile__identity"><img src={teacherAvatar} alt={student.name} /><div><h2>{student.name}</h2><p>Kenyatta Primary School</p><b>Curriculum: 8-4-4</b></div></div><section className="teacher-student-profile__streak"><div><Flame size={15} /> Weekly Streak <a href="#streak">View</a></div><div className="teacher-student-profile__week">{['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'].map((day, index) => <span key={day}><small>{day}</small><b>{index < 3 ? '✓' : 15 + index}</b></span>)}</div></section><Schedule /><section className="teacher-student-profile__reports"><h3>Grade Reports</h3>{[1, 2, 3].map(item => <button type="button" key={item}><span><b>First Term 2025</b><small>12 Jan 2024 4.30 PM</small></span><Download size={16} /></button>)}</section></aside><main className="teacher-student-profile__main"><nav className="teacher-student-profile__tabs">{(['overview', 'lessons', 'reports'] as const).map(item => <button className={tab === item ? 'is-active' : ''} type="button" onClick={() => setTab(item)} key={item}>{item[0].toUpperCase() + item.slice(1)}</button>)}</nav>{tab === 'overview' ? <Overview /> : <section className="teacher-student-profile__placeholder"><h2>{tab === 'lessons' ? 'Lessons' : 'Reports'}</h2><p>{tab === 'lessons' ? 'Review this student’s lesson activity and completion history.' : 'Review this student’s academic reports and downloadable records.'}</p></section>}</main></div></section></div>
}
function Schedule() { return <section className="teacher-student-profile__schedule"><h3>TimeTable <small>• Today</small><a href="/teacher/timetable">View Calendar</a></h3>{['Physics Tuition', 'Physics Tuition', 'Physics Tuition'].map((item, index) => <p key={`${item}-${index}`}><small>3.30 PM</small><span>Grade 3<br /><b>{item}</b></span></p>)}</section> }
function Overview() { return <div className="teacher-student-profile__overview"><h3>Performance Overview</h3><section className="teacher-student-profile__performance"><div><small>Avg Grade</small><strong>A- 80 Points</strong><span>Position: <b>3/200</b></span></div><div><small>Attendance Rate</small><strong>70%</strong><span>As per lesson attendance records</span></div><div className="teacher-student-profile__gauge"><i /><span>Student is top<br /><b>40%</b></span></div></section><div className="teacher-student-profile__subject-row"><section><header><h3>Subject Performance by Assignment</h3><a href="#report">View Report</a><button type="button">Assignments</button></header><div className="teacher-student-profile__subjects">{[['Maths', 'A', 78], ['Eng', 'B', 55], ['Kis', 'C', 37], ['Phy', 'C', 20], ['Chem', 'D', 6], ['Geo', 'D', 6]].map(([name, grade, value]) => <div key={String(name)}><span><b>{name}</b> Assignments Completed: 10/20</span><i><em style={{ width: `${value}%` }} /></i><strong>{grade}</strong></div>)}</div></section><Chart title="No of Assignments" /></div><section className="teacher-student-profile__trend"><header><h3>Academic Performance Trend</h3><span><i /> Student　<i /> Peer Average</span></header><div className="teacher-student-profile__bars">{[28, 44, 76, 63, 47, 31, 83, 62].map((height, index) => <span key={index}><i style={{ height: `${height}%` }} /><b style={{ height: `${Math.max(height - 5, 10)}%` }} /><small>{['Math', 'Eng', 'Kis', 'Phy', 'Chem', 'Bio', 'Geo', 'CRE'][index]}</small></span>)}</div></section><section className="teacher-student-profile__top-subjects"><h3>Top Subjects</h3><p>Top 3 subjects performance</p><div className="teacher-student-profile__rings"><i /><i /><i /></div><span>Math　94%　 Phy　85%　 Chem　70%</span></section></div> }
function Chart({ title }: { title: string }) { return <section className="teacher-student-profile__chart"><header><h3>{title}</h3><button type="button"><ChevronDown size={14} /> Subject</button></header><div className="teacher-student-profile__line-chart"><svg viewBox="0 0 360 210" role="img" aria-label="Assignments trend"><path d="M10 165 C 45 145, 55 160, 78 145 S 120 155, 145 112 S 190 130, 220 95 S 280 120, 350 52" /></svg><span>Jan　　　　　　 Mar　　　　 May　　　　 Jul　　　 Sep　　　　 Nov　　 Dec</span></div></section> }
