import { CalendarDays, ChevronDown, ChevronLeft, ChevronRight, Clock3, Filter, Plus, SlidersHorizontal, X } from 'lucide-react'
import { useState } from 'react'
import TeacherDashboardLayout from './TeacherDashboardLayout'
import speaker from '../../assets/images/student-flow/speaker.svg'
import '../../styles/pages/teacher-timetable.css'

type CalendarView = 'month' | 'day' | 'week'
type EventItem = { title: string; time: string; type: 'lesson' | 'exam' | 'event' }
const events: EventItem[] = [
    { title: 'Grade 3 Parent Meeting', time: 'Mon, 30 Jan 2023 8.30 PM', type: 'exam' },
    { title: 'Chemistry Assignment', time: 'Wed, 1 Feb 2023 2.30 PM', type: 'lesson' },
    { title: 'PTO Grade 3', time: 'Mon, 30 Jan 2023 11.00 AM', type: 'event' },
]
const monthNames = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']

export default function TeacherTimetablePage() {
    const [tab, setTab] = useState<'timetable' | 'plan'>('timetable')
    const [view, setView] = useState<CalendarView>('month')
    const [event, setEvent] = useState<EventItem | null>(null)
    return <TeacherDashboardLayout activePath="/teacher/timetable"><section className="teacher-timetable-page" aria-labelledby="teacher-timetable-title"><div className="teacher-timetable-page__layout"><AccountRail /><div className="teacher-timetable-page__content"><header className="teacher-timetable-page__header"><div><h1 id="teacher-timetable-title">My Timetable</h1><p>Manage lesson schedule</p></div><span>Timezone: <a href="#timezone">GMT+03</a></span></header><nav className="teacher-timetable-page__tabs"><button className={tab === 'timetable' ? 'is-active' : ''} type="button" onClick={() => setTab('timetable')}>My Timetable</button><button className={tab === 'plan' ? 'is-active' : ''} type="button" onClick={() => setTab('plan')}>Lesson Plan</button></nav>{tab === 'timetable' ? <TimetableView view={view} setView={setView} onEvent={setEvent} /> : <LessonPlan />}</div></div></section>{event && <EventModal event={event} onClose={() => setEvent(null)} />}</TeacherDashboardLayout>
}

function AccountRail() { return <aside className="teacher-timetable-page__account"><div className="teacher-timetable-page__school-mark"><CalendarDays size={27} /></div><h2>Mathematic Excellence<br />Academy</h2><span className="teacher-timetable-page__school-tag">Online School</span><p>Contact Information</p><strong>+254712 345 678</strong><strong>mathematicexcel@gmail.com</strong><button type="button">Switch Account</button><div className="teacher-timetable-page__referral"><img src={speaker} alt="" /><div><b>Refer &amp; Earn with Sqooli</b><small>Share your unique link to students &amp; parents to join Sqooli</small><button type="button">Copy Link</button></div></div></aside> }
function TimetableView({ view, setView, onEvent }: { view: CalendarView; setView: (view: CalendarView) => void; onEvent: (event: EventItem) => void }) {
    const [monthIndex, setMonthIndex] = useState(1)
    const [year, setYear] = useState(2023)
    const [selectedDate, setSelectedDate] = useState(10)
    const shiftMonth = (amount: number) => {
        const next = monthIndex + amount
        if (next < 0) { setMonthIndex(11); setYear(value => value - 1) }
        else if (next > 11) { setMonthIndex(0); setYear(value => value + 1) }
        else setMonthIndex(next)
    }
    const monthLabel = `${monthNames[monthIndex]} ${year}`
    return <div className="teacher-timetable-page__workspace"><aside className="teacher-timetable-page__sidebar"><MiniCalendar monthLabel={monthLabel} selectedDate={selectedDate} onShiftMonth={shiftMonth} onSelectDate={setSelectedDate} /><section className="teacher-timetable-page__key"><h3>Key</h3><p><i className="is-lesson" /> Lesson</p><p><i className="is-exam" /> Exam</p><p><i className="is-event" /> School Event</p></section></aside><main className="teacher-timetable-page__calendar"><header><h2>{view === 'month' ? monthLabel : view === 'day' ? `Wed, ${selectedDate} ${monthNames[monthIndex].slice(0, 3)}` : 'Sun - Sat'}</h2><div><button type="button"><SlidersHorizontal size={15} /> Add filters</button><div className="teacher-timetable-page__view-switcher" aria-label="Calendar view">{(['month', 'day', 'week'] as CalendarView[]).map(item => <button className={view === item ? 'is-active' : ''} type="button" key={item} onClick={() => setView(item)}>{item[0].toUpperCase() + item.slice(1)}</button>)}</div></div></header>{view === 'month' ? <MonthView selectedDate={selectedDate} onSelectDate={setSelectedDate} onEvent={onEvent} /> : <TimeView view={view} onEvent={onEvent} />}</main></div>
}
function MiniCalendar({ monthLabel, selectedDate, onShiftMonth, onSelectDate }: { monthLabel: string; selectedDate: number; onShiftMonth: (amount: number) => void; onSelectDate: (date: number) => void }) { const days = ['30', '31', ...Array.from({ length: 28 }, (_, index) => String(index + 1)), '1', '2', '3', '4', '5']; return <div className="teacher-timetable-page__mini-calendar"><header><button type="button" aria-label="Previous month" onClick={() => onShiftMonth(-1)}><ChevronLeft size={15} /></button><b>{monthLabel}</b><button type="button" aria-label="Next month" onClick={() => onShiftMonth(1)}><ChevronRight size={15} /></button></header><div className="teacher-timetable-page__mini-weekdays">{['Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa', 'Su'].map(day => <b key={day}>{day}</b>)}</div><div className="teacher-timetable-page__mini-days">{days.map((day, index) => <button className={day === String(selectedDate) && index > 1 && index < 30 ? 'is-selected' : ''} type="button" onClick={() => index > 1 && index < 30 && onSelectDate(Number(day))} key={`${day}-${index}`}>{day}</button>)}</div></div> }
function MonthView({ selectedDate, onSelectDate, onEvent }: { selectedDate: number; onSelectDate: (date: number) => void; onEvent: (event: EventItem) => void }) { const days = Array.from({ length: 28 }, (_, index) => index + 1); return <div className="teacher-timetable-page__month-view"><div className="teacher-timetable-page__month-weekdays">{['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'].map(day => <b key={day}>{day}</b>)}</div><div className="teacher-timetable-page__month-grid">{days.map(day => <div className={day === selectedDate ? 'is-selected' : ''} role="button" tabIndex={0} onClick={() => onSelectDate(day)} onKeyDown={event => event.key === 'Enter' && onSelectDate(day)} key={day}><small>{day}</small>{day === 1 && <EventButton event={events[2]} onEvent={onEvent} />}{day === 1 && <EventButton event={events[0]} onEvent={onEvent} />}{day === 14 && <EventButton event={events[1]} onEvent={onEvent} />}</div>)}</div></div> }
function TimeView({ view, onEvent }: { view: CalendarView; onEvent: (event: EventItem) => void }) { const hours = ['12 AM', '1 AM', '2 AM', '3 AM', '4 AM', '5 AM', '6 AM', '7 AM', '8 AM', '9 AM', '10 AM', '11 AM', '12 PM', '1 PM']; const days = view === 'day' ? [{ day: 'Wed', date: '1' }] : [{ day: 'Sun', date: '28' }, { day: 'Mon', date: '29' }, { day: 'Tue', date: '31' }, { day: 'Wed', date: '1' }, { day: 'Thu', date: '2' }, { day: 'Fri', date: '3' }, { day: 'Sat', date: '4' }]; return <div className={`teacher-timetable-page__time-view${view === 'day' ? ' is-day' : ''}`}><div className="teacher-timetable-page__time-head"><span />{days.map(item => <b key={item.day}><span>{item.day}</span><strong className={item.day === 'Wed' ? 'is-selected' : ''}>{item.date}</strong></b>)}</div>{hours.map((hour, index) => <div className="teacher-timetable-page__time-row" key={hour}><small>{hour}</small>{days.map((_, column) => <div key={column}>{(index === 4 && column === 0) || (index === 8 && column < 2) ? <EventButton event={events[0]} onEvent={onEvent} /> : null}</div>)}</div>)}</div> }
function EventButton({ event, onEvent }: { event: EventItem; onEvent: (event: EventItem) => void }) { return <button className={`teacher-timetable-page__event is-${event.type}`} type="button" onClick={() => onEvent(event)}>{event.time.split(' ').slice(-2).join(' ')} {event.title}</button> }
function LessonPlan() { const [year, setYear] = useState('2025'); const [month, setMonth] = useState('Mar'); return <section className="teacher-timetable-page__lesson-plan"><header><div><b>28 Feb {year} - 1 Mar {year}</b><a href="#next">Next Week</a></div><div className="teacher-timetable-page__months"><label><select value={year} onChange={event => setYear(event.target.value)} aria-label="Lesson plan year"><option>2025</option><option>2026</option><option>2027</option></select><ChevronDown size={14} /></label>{['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'].map(item => <button className={month === item ? 'is-active' : ''} onClick={() => setMonth(item)} type="button" key={item}>{item}</button>)}</div></header><div className="teacher-timetable-page__plan-grid"><div className="is-time">Time</div>{['Mon', 'Tue', 'Wed', 'Thu', 'Fri'].map(day => <b key={day}>{day}<span>{day === 'Mon' ? '28' : day === 'Tue' ? '29' : day === 'Wed' ? '30' : day === 'Thu' ? '31' : '1'}</span></b>)}{['9:00-10:00', '10:00-11:00', '11:00-12:00', '12:00-1:00', '1:00-2:00', '2:00-3:00', '3:00-4:00', '4:00-5:00'].map((time, row) => <><span className="teacher-timetable-page__plan-time" key={`${time}-time`}>{time}</span>{Array.from({ length: 5 }, (_, column) => <button className={row % 3 === 0 && column % 2 === 0 ? 'is-booked' : row === 1 ? 'is-break' : row % 2 === 0 ? 'is-create' : 'is-unavailable'} type="button" key={`${time}-${column}`}>{row % 3 === 0 && column % 2 === 0 ? <><small>6301 | Program Name | Grade 6</small><b>Arithmetics 1</b><em>60 min</em></> : row === 1 ? 'Break' : row % 2 === 0 ? <><Plus size={14} /> Create Lesson</> : 'unavailable'}</button>)}</>)}</div></section> }
function EventModal({ event, onClose }: { event: EventItem; onClose: () => void }) { return <div className="teacher-timetable-event__backdrop" onMouseDown={mouseEvent => mouseEvent.target === mouseEvent.currentTarget && onClose()}><section className="teacher-timetable-event" role="dialog" aria-modal="true" aria-labelledby="timetable-event-title"><header><div><CalendarDays size={16} /> Calendar</div><button type="button" aria-label="Close event" onClick={onClose}><X size={20} /></button></header><h2 id="timetable-event-title">{event.title}</h2><p><Clock3 size={18} /> {event.time}</p><p><Filter size={18} /> Please Note Of Upcoming {event.title}</p><button className="is-primary" type="button" onClick={onClose}>View</button></section></div> }
