import { Award, BookOpen, Check, ChevronDown, ChevronRight, Clock3, FileText, FolderOpen, Globe2, MessageCircle, PlayCircle, Send, Star, X } from 'lucide-react'
import { useState } from 'react'
import '../../styles/pages/teacher-student-view.css'

type StudentTab = 'about' | 'curriculum' | 'resources' | 'forum' | 'assignments'

const tabs: Array<[StudentTab, string]> = [['about', 'About'], ['curriculum', 'Curriculum'], ['resources', 'Resources'], ['forum', 'Forum'], ['assignments', 'Assignments & Exams']]
const learningPoints = Array.from({ length: 6 }, () => 'Gain an immersive understanding of the practices and skills needed to succeed in an entry-level project management role')
const lessonContent = ['Video Introduction', 'Video Introduction', 'What you will learn in this lesson', 'Notes Example', 'Assignment Example', 'What you will learn in this lesson']

export default function TeacherStudentViewModal({ onClose }: { onClose: () => void }) {
    const [activeTab, setActiveTab] = useState<StudentTab>('about')
    return <div className="teacher-student-view__backdrop" onMouseDown={event => event.target === event.currentTarget && onClose()}>
        <section className="teacher-student-view" role="dialog" aria-modal="true" aria-labelledby="student-view-title">
            <header className="teacher-student-view__topbar"><div><BookOpen size={15} /> <span>Lessons</span><ChevronRight size={14} /><b>Physics– Form 4</b></div><button type="button" aria-label="Close student view" onClick={onClose}><X size={20} /></button></header>
            <div className="teacher-student-view__hero"><div className="teacher-student-view__art-strip" /><div className="teacher-student-view__hero-copy"><h1 id="student-view-title">Physics– Form 4</h1><div className="teacher-student-view__badges"><b>Physics</b><b>Curriculum: 8-4-4</b><b>Catch up</b><span><Clock3 size={13} /> Last Updated: 10 Jun 2025 11.00 AM</span><span><Globe2 size={13} /> Language: English</span></div><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum...<a href="#student-about">show more</a></p><h2>KES 200/ Lesson</h2><div className="teacher-student-view__stats"><Stat icon={<span className="teacher-student-view__avatar">J</span>} value="Jane Doe" label="Tutor" /><Stat icon={<Star size={18} fill="currentColor" />} value="4.5 ★" label="3,984 ratings" /><Stat value="3,984" label="Enrolled Students" /><Stat value="Form 4" label="Level" /><Stat value="20" label="Lessons" /><Stat value="20" label="Quizzes & Assignments" /><Stat value="8" label="Total Hours" /><Stat icon={<Award size={16} fill="currentColor" />} value="" label="Certification Awarded" /></div></div></div>
            <nav className="teacher-student-view__tabs" aria-label="Student lesson navigation">{tabs.map(([key, label]) => <button type="button" className={activeTab === key ? 'is-active' : ''} onClick={() => setActiveTab(key)} key={key}>{label}</button>)}</nav>
            <main className="teacher-student-view__body">{activeTab === 'about' ? <About /> : <TabPlaceholder tab={activeTab} />}</main>
        </section>
    </div>
}

function Stat({ icon, value, label }: { icon?: React.ReactNode; value: string; label: string }) { return <div>{icon && <i>{icon}</i>}{value && <strong>{value}</strong>}<small>{label}</small></div> }
function About() { return <div id="student-about"><section><h2>What you will learn</h2><div className="teacher-student-view__learning-grid">{learningPoints.map((point, index) => <p key={index}><Check size={14} />{point}</p>)}</div></section><section><h2>Related Topics</h2><div className="teacher-student-view__pills"><span>Physics</span><span>Programming</span><span>Programming</span></div></section><section><h2>Physics Form 4 Term 3</h2><p className="teacher-student-view__copy">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum...<a href="#student-about">show more</a></p><Topic title="Topic 1" open /><Topic title="Topic 2" /><Topic title="Topic 3" /><Topic title="Topic 4" /></section><section><h2>Testimonials</h2><div className="teacher-student-view__testimonials">{Array.from({ length: 4 }, (_, i) => <article key={i}><b>OR</b><strong>Olivia Rhye</strong><p>“Lorem ipsum dolor sit amet, consectetur adipiscing elit. Tincidunt nunc ipsum tempor purus vitae id.”</p></article>)}</div></section><section><h2>Resources</h2><div className="teacher-student-view__resources"><button type="button"><BookOpen size={15} />10 Books<ChevronRight size={15} /></button><button type="button"><FolderOpen size={15} />10 Notes<ChevronRight size={15} /></button><button type="button"><PlayCircle size={15} />10 Videos<ChevronRight size={15} /></button></div></section><section className="teacher-student-view__forum"><h2>Forum</h2>{Array.from({ length: 3 }, (_, i) => <article key={i}><b>OR</b><div><strong>Olivia Rhye <small>2 mins ago</small></strong><p>“Lorem ipsum dolor sit amet, consectetur adipiscing elit. Tincidunt nunc ipsum tempor purus vitae id.”</p><span><MessageCircle size={14} /> 20</span></div><a href="#student-forum">Reply</a></article>)}<button className="teacher-student-view__post" type="button"><Send size={14} /> Post Comment</button></section></div> }
function Topic({ title, open }: { title: string; open?: boolean }) { return <article className="teacher-student-view__topic"><header><div><strong>{title}</strong><small>4 Lectures · 50 min</small></div><ChevronDown size={16} /></header>{open && <div className="teacher-student-view__topic-content"><h3>What you will learn</h3>{learningPoints.slice(0, 2).map((point, index) => <p key={index}><Check size={14} />{point}</p>)}<h3>Related Topics</h3><div className="teacher-student-view__pills"><span>Physics</span><span>Programming</span><span>Programming</span></div><h3>Lesson Content</h3>{lessonContent.map(item => <span className="teacher-student-view__content-row" key={item}><FileText size={14} />{item}<em>3.08 min</em></span>)}</div>}</article> }
function TabPlaceholder({ tab }: { tab: StudentTab }) {
    if (tab === 'curriculum') return <section className="teacher-student-view__tab-content"><h2>Physics Form 4 Term 3</h2><p className="teacher-student-view__copy">Explore the lesson topics, learning outcomes, and included content.</p><Topic title="Topic 1" open /><Topic title="Topic 2" /><Topic title="Topic 3" /><Topic title="Topic 4" /></section>
    if (tab === 'resources') return <section className="teacher-student-view__tab-content"><h2>Resources</h2><p className="teacher-student-view__copy">Learning materials attached to this lesson.</p><div className="teacher-student-view__resources"><button type="button"><BookOpen size={15} />10 Books<ChevronRight size={15} /></button><button type="button"><FolderOpen size={15} />10 Notes<ChevronRight size={15} /></button><button type="button"><PlayCircle size={15} />10 Videos<ChevronRight size={15} /></button></div></section>
    if (tab === 'forum') return <section className="teacher-student-view__tab-content teacher-student-view__forum"><div className="teacher-student-view__section-heading"><h2>Forum</h2><a href="/teacher/forums">Go to Forums</a></div>{Array.from({ length: 4 }, (_, i) => <article key={i}><b>OR</b><div><strong>{i % 2 ? 'John Kamau' : 'Olivia Rhye'} <small>2 mins ago</small></strong><p>“Lorem ipsum dolor sit amet, consectetur adipiscing elit. Tincidunt nunc ipsum tempor purus vitae id.”</p><span><MessageCircle size={14} /> 20</span></div><a href="/teacher/forums">Reply</a></article>)}<button className="teacher-student-view__post" type="button"><Send size={14} /> Post Comment</button></section>
    return <section className="teacher-student-view__tab-content"><h2>Assignments &amp; Exams</h2><p className="teacher-student-view__copy">Assessments included in this lesson.</p><div className="teacher-student-view__assignment-list">{['Test Assignment 1', 'Test Assignment 2', 'Mid-term Quiz'].map(item => <button type="button" key={item}><FileText size={15} /><span>{item}<small>View submission details</small></span><ChevronRight size={15} /></button>)}</div></section>
}
