import { ArrowLeft, ArrowRight, BookOpen, Check, ChevronRight, Edit3, Plus, Trash2, X } from 'lucide-react'
import { useState, type ReactNode } from 'react'
import '../../styles/pages/teacher-create-lesson.css'

type Props = { onClose: () => void; onSubmitted?: () => void }
type Step = 1 | 2 | 3 | 4 | 5 | 6
type Lecture = { title: string; description: string; items: string[] }
type Section = { title: string; lectures: Lecture[] }

const stepLabels = ['Basic Information', 'Learning Objectives', 'Lesson Requirements', 'Lesson Content', 'Pricing', 'Preview']
const topics = ['Programming', 'Development', 'Business', 'Science', 'History', 'Social Studies', 'Christian Religious Education', 'Physics', 'Geography']

export default function TeacherCreateLessonModal({ onClose, onSubmitted }: Props) {
	const [step, setStep] = useState<Step>(1)
	const [title, setTitle] = useState('')
	const [type, setType] = useState('')
	const [description, setDescription] = useState('')
	const [subProgram, setSubProgram] = useState('')
	const [subject, setSubject] = useState('')
	const [date, setDate] = useState('')
	const [time, setTime] = useState('')
	const [duration, setDuration] = useState('0')
	const [repeat, setRepeat] = useState('')
	const [selectedTopics, setSelectedTopics] = useState(['Social Studies'])
	const [objectives, setObjectives] = useState(['', ''])
	const [requirements, setRequirements] = useState('')
	const [sections, setSections] = useState<Section[]>([{ title: 'Section 1', lectures: [] }])
	const [price, setPrice] = useState('0')
	const [revenueRows, setRevenueRows] = useState<string[]>([])
	const [revenueOpen, setRevenueOpen] = useState(false)

	const toggleTopic = (topic: string) => setSelectedTopics((items) => items.includes(topic) ? items.filter((item) => item !== topic) : items.length < 5 ? [...items, topic] : items)
	const next = () => {
		if (step === 6) { window.sessionStorage.setItem('sqooli-teacher-lesson-created', 'true'); onSubmitted?.(); onClose(); return }
		setStep((value) => (value + 1) as Step)
	}
	const updateSection = (sectionIndex: number, update: Partial<Section>) => setSections((items) => items.map((item, index) => index === sectionIndex ? { ...item, ...update } : item))
	const addSection = () => setSections((items) => [...items, { title: `Section ${items.length + 1}`, lectures: [] }])
	const addLecture = (sectionIndex: number) => setSections((items) => items.map((section, index) => index === sectionIndex ? { ...section, lectures: [...section.lectures, { title: `Lecture ${section.lectures.length + 1}`, description: '', items: [] }] } : section))
	const updateLecture = (sectionIndex: number, lectureIndex: number, update: Partial<Lecture>) => setSections((items) => items.map((section, index) => index === sectionIndex ? { ...section, lectures: section.lectures.map((lecture, itemIndex) => itemIndex === lectureIndex ? { ...lecture, ...update } : lecture) } : section))
	const removeLecture = (sectionIndex: number, lectureIndex: number) => setSections((items) => items.map((section, index) => index === sectionIndex ? { ...section, lectures: section.lectures.filter((_, itemIndex) => itemIndex !== lectureIndex) } : section))
	const addContent = (sectionIndex: number, lectureIndex: number, item: string) => setSections((items) => items.map((section, index) => index === sectionIndex ? { ...section, lectures: section.lectures.map((lecture, itemIndex) => itemIndex === lectureIndex ? { ...lecture, items: [...lecture.items, item] } : lecture) } : section))

	return <div className="teacher-create-lesson-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose() }}>
		<section className="teacher-create-lesson" role="dialog" aria-modal="true" aria-labelledby="create-lesson-title">
			<header className="teacher-create-lesson__top"><span><BookOpen size={15} /> Lessons <ChevronRight size={14} /> <b id="create-lesson-title">Create Lesson</b></span><button type="button" aria-label="Close create lesson" onClick={onClose}><X size={22} /></button></header>
			<div className="teacher-create-lesson__body">
				<nav className="teacher-create-lesson__steps" aria-label="Create lesson steps">{stepLabels.map((label, index) => { const number = (index + 1) as Step; return <button type="button" key={label} className={`${step === number ? 'is-active' : ''}${number < step ? ' is-complete' : ''}`} onClick={() => number <= step && setStep(number)}><span>Step {number}/6 {number < step && <Check size={14} />}</span><strong>{label}</strong></button> })}</nav>
				<main className="teacher-create-lesson__content">
					{step === 1 && <BasicInformation {...{ title, setTitle, type, setType, description, setDescription, subProgram, setSubProgram, subject, setSubject, date, setDate, time, setTime, duration, setDuration, repeat, setRepeat, selectedTopics, toggleTopic }} />}
					{step === 2 && <Objectives objectives={objectives} setObjectives={setObjectives} />}
					{step === 3 && <RichText title="Lesson Requirements" subtitle="Add summary of what students require before taking your lesson" value={requirements} setValue={setRequirements} />}
					{step === 4 && <LessonContent sections={sections} updateSection={updateSection} addSection={addSection} addLecture={addLecture} updateLecture={updateLecture} removeLecture={removeLecture} addContent={addContent} />}
					{step === 5 && <Pricing price={price} setPrice={setPrice} revenueRows={revenueRows} onRevenue={() => setRevenueOpen(true)} onRemoveRevenue={(index) => setRevenueRows((items) => items.filter((_, itemIndex) => itemIndex !== index))} />}
					{step === 6 && <Preview title={title || 'Untitled Lesson'} description={description} price={price} sections={sections} objectives={objectives} />}
					<div className="teacher-create-lesson__actions"><button type="button" className="teacher-create-lesson__back" onClick={() => step === 1 ? onClose() : setStep((value) => (value - 1) as Step)}><ArrowLeft size={17} /> Back</button><button type="button" className="teacher-create-lesson__continue" onClick={next}>{step === 5 ? 'Save & Continue' : step === 6 ? 'Submit Lesson' : 'Save & Continue'} <ArrowRight size={17} /></button></div>
				</main>
			</div>
			{revenueOpen && <RevenueShareModal onClose={() => setRevenueOpen(false)} onSave={() => { setRevenueRows((items) => [...items, '24 Jan 2025 11.00 AM']); setRevenueOpen(false) }} />}
		</section>
	</div>
}

type BasicInformationProps = { title: string; setTitle: (value: string) => void; type: string; setType: (value: string) => void; description: string; setDescription: (value: string) => void; subProgram: string; setSubProgram: (value: string) => void; subject: string; setSubject: (value: string) => void; date: string; setDate: (value: string) => void; time: string; setTime: (value: string) => void; duration: string; setDuration: (value: string) => void; repeat: string; setRepeat: (value: string) => void; selectedTopics: string[]; toggleTopic: (topic: string) => void }
function BasicInformation({ title, setTitle, type, setType, description, setDescription, subProgram, setSubProgram, subject, setSubject, date, setDate, time, setTime, duration, setDuration, repeat, setRepeat, selectedTopics, toggleTopic }: BasicInformationProps) { return <StepPanel title="Basic Information" subtitle="Add basic information about your lesson"><div className="teacher-create-lesson__form-grid"><Field label="Lesson Title" value={title} onChange={setTitle} /><SelectField label="Lesson Type" value={type} onChange={setType} options={['Lecture', 'Workshop', 'Tutoring']} /></div><RichEditor label="Lesson Description" value={description} onChange={setDescription} /><SelectField label="Program" value="CBC First Term 2026 Grade 6" options={[]} /><div className="teacher-create-lesson__program"><strong>CBC First Term 2026 Grade 6<small>Date Created: 11 Jan 2025</small></strong><span>Curriculum<br /><b>CBC</b></span><span>Grade<br /><b>Grade 6</b></span><span>Sub-programs<br /><b>4</b></span></div><div className="teacher-create-lesson__form-grid"><SelectField label="Sub-Program" value={subProgram} onChange={setSubProgram} options={['Select...', 'Term 1', 'Term 2']} /><SelectField label="Subject" value={subject} onChange={setSubject} options={['Select...', 'Mathematics', 'Science', 'Social Studies']} /></div><div className="teacher-create-lesson__topics"><strong>Related Topics</strong><small>Choose 5 related topics to your lesson title</small><div>{topics.map((topic) => <button type="button" className={selectedTopics.includes(topic) ? 'is-selected' : ''} onClick={() => toggleTopic(topic)} key={topic}><Plus size={13} /> {topic}{selectedTopics.includes(topic) && topic === 'Social Studies' && <X size={12} />}</button>)}</div></div><div className="teacher-create-lesson__timing"><strong>Lesson Timing</strong><small>Select start date and time for your lesson</small><div className="teacher-create-lesson__form-grid teacher-create-lesson__form-grid--three"><Field label="Start Date" type="date" value={date} onChange={setDate} /><SelectField label="Lesson Time" value={time} onChange={setTime} options={['Select...', '08:00 AM', '11:00 AM', '02:00 PM']} /><Field label="Duration" value={duration} onChange={(value: string) => setDuration(value.replace(/\D/g, ''))} suffix="Minutes" /></div><SelectField label="Repeat" value={repeat} onChange={setRepeat} options={['Select...', 'Does not repeat', 'Weekly', 'Monthly']} /></div></StepPanel> }

function Objectives({ objectives, setObjectives }: { objectives: string[]; setObjectives: (items: string[]) => void }) { return <StepPanel title="Learning Objectives" subtitle="Add summary of what your students can expect to learn"><div className="teacher-create-lesson__objectives">{objectives.map((objective, index) => <label key={index}><input maxLength={60} value={objective} onChange={(event) => setObjectives(objectives.map((item, itemIndex) => itemIndex === index ? event.target.value : item))} placeholder="Enter Learning Objective" /><span>{60 - objective.length} characters <button type="button" aria-label="Delete objective" onClick={() => setObjectives(objectives.length > 1 ? objectives.filter((_, itemIndex) => itemIndex !== index) : [''])}><Trash2 size={15} /></button></span></label>)}</div><button type="button" className="teacher-create-lesson__outline-button" onClick={() => setObjectives([...objectives, ''])}><Plus size={15} /> Add Objective</button></StepPanel> }

function RichText({ title, subtitle, value, setValue }: { title: string; subtitle: string; value: string; setValue: (value: string) => void }) { return <StepPanel title={title} subtitle={subtitle}><RichEditor label={title} value={value} onChange={setValue} /></StepPanel> }
function RichEditor({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="teacher-create-lesson__label">{label}<textarea className="is-large" value={value} onChange={(event) => onChange(event.target.value)} placeholder="Enter a description..." /><span className="teacher-create-lesson__toolbar">Undo / Redo · Sans Serif · <b>B</b> · <i>I</i> · <u>U</u> · Align · Lists</span></label> }

type LessonContentProps = { sections: Section[]; updateSection: (index: number, update: Partial<Section>) => void; addSection: () => void; addLecture: (index: number) => void; updateLecture: (sectionIndex: number, lectureIndex: number, update: Partial<Lecture>) => void; removeLecture: (sectionIndex: number, lectureIndex: number) => void; addContent: (sectionIndex: number, lectureIndex: number, item: string) => void }
function LessonContent({ sections, updateSection, addSection, addLecture, updateLecture, removeLecture, addContent }: LessonContentProps) { return <StepPanel title="Lesson Content" subtitle="Select the type of content that will be included in your lesson">{sections.map((section, sectionIndex) => <div className="teacher-create-lesson__section" key={sectionIndex}><div className="teacher-create-lesson__section-head"><input value={section.title} onChange={(event) => updateSection(sectionIndex, { title: event.target.value })} /><button type="button" aria-label="Delete section" onClick={() => sections.length > 1 && updateSection(sectionIndex, { lectures: [] })}><Trash2 size={14} /></button></div>{section.lectures.map((lecture, lectureIndex) => <div className="teacher-create-lesson__lesson" key={lectureIndex}><div className="teacher-create-lesson__lesson-head"><input value={lecture.title} onChange={(event) => updateLecture(sectionIndex, lectureIndex, { title: event.target.value })} /><button type="button" aria-label="Edit lecture"><Edit3 size={14} /></button><button type="button" aria-label="Delete lecture" onClick={() => removeLecture(sectionIndex, lectureIndex)}><Trash2 size={14} /></button></div><label>Description<textarea value={lecture.description} onChange={(event) => updateLecture(sectionIndex, lectureIndex, { description: event.target.value })} placeholder="Enter description..." /></label>{lecture.items.length > 0 && <div className="teacher-create-lesson__content-items">{lecture.items.map((item, itemIndex) => <span key={itemIndex}>{item}<button type="button" onClick={() => updateLecture(sectionIndex, lectureIndex, { items: lecture.items.filter((_, index) => index !== itemIndex) })}><X size={12} /></button></span>)}</div>}<div className="teacher-create-lesson__chips">{['Quiz', 'Assignment', 'Exam', 'Other Resources', 'Video'].map((item) => <button type="button" key={item} onClick={() => addContent(sectionIndex, lectureIndex, item)}><Plus size={14} /> {item}</button>)}</div></div>)}<button type="button" className="teacher-create-lesson__outline-button" onClick={() => addLecture(sectionIndex)}><Plus size={15} /> Add Lecture</button></div>)}<button type="button" className="teacher-create-lesson__section-add" onClick={addSection}><Plus size={15} /> Add Section</button></StepPanel> }

function Pricing({ price, setPrice, revenueRows, onRevenue, onRemoveRevenue }: { price: string; setPrice: (value: string) => void; revenueRows: string[]; onRevenue: () => void; onRemoveRevenue: (index: number) => void }) { const amount = Number(price) || 0; const fee = amount * .2; return <StepPanel title="Pricing" subtitle="Setup your pricing for each lesson"><div className="teacher-create-lesson__pricing"><label>Rate per Lesson<small>Total client will see</small><input inputMode="decimal" value={`KES ${price}`} onChange={(event) => setPrice(event.target.value.replace(/\D/g, ''))} /></label><label>Sqooli Service Fee<small>Sqooli charges 20% on every transaction</small><input value={`KES ${fee.toFixed(2)}`} readOnly /></label><label>What you will receive<small>The estimated amount after service Payments</small><input value={`KES ${(amount - fee).toFixed(2)}`} readOnly /></label></div><h3>Do you have additional revenue shares?</h3><p>Add other custom deductions on your earnings</p><button type="button" className="teacher-create-lesson__outline-button" onClick={onRevenue}><Plus size={15} /> Add Revenue Shares</button>{revenueRows.length > 0 && <div className="teacher-create-lesson__revenue-table"><b>User</b><b>Commission Type</b><b>Value</b><b>Actions</b>{revenueRows.map((row, index) => <div key={`${row}-${index}`}><span>{row}</span><span>Fixed Value</span><span>50</span><span><button type="button"><Edit3 size={14} /></button><button type="button" onClick={() => onRemoveRevenue(index)}><Trash2 size={14} /></button></span></div>)}</div>}</StepPanel> }

function Preview({ title, description, price, sections, objectives }: { title: string; description: string; price: string; sections: Section[]; objectives: string[] }) { return <StepPanel title="Preview" subtitle="Review your lesson before submitting"><div className="teacher-create-lesson__preview"><h2>{title}</h2><p>{description || 'No lesson description added yet.'}</p><hr /><strong>What students will learn</strong><ul>{objectives.filter(Boolean).map((objective) => <li key={objective}>{objective}</li>)}</ul><strong>Lesson Details</strong><dl><dt>Content sections</dt><dd>{sections.length}</dd><dt>Price per Lesson</dt><dd>KES {price || '0'}</dd><dt>Status</dt><dd>Ready to submit</dd></dl></div></StepPanel> }
function StepPanel({ title, subtitle, children }: { title: string; subtitle: string; children: ReactNode }) { return <section className="teacher-create-lesson__panel"><h1>{title}</h1><p>{subtitle}</p>{children}</section> }
function Field({ label, value, onChange, placeholder, suffix, type = 'text' }: { label: string; value: string; onChange: (value: string) => void; placeholder?: string; suffix?: string; type?: string }) { return <label className="teacher-create-lesson__label">{label}<span className="teacher-create-lesson__input"><input type={type} value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} />{suffix && <em>{suffix}</em>}</span></label> }
function SelectField({ label, value, onChange, options }: { label: string; value: string; onChange?: (value: string) => void; options: string[] }) { return <label className="teacher-create-lesson__label">{label}<span className="teacher-create-lesson__select"><select value={value} onChange={(event) => onChange?.(event.target.value)} disabled={!onChange}>{options.length === 0 ? <option>{value}</option> : options.map((option) => <option key={option} value={option}>{option}</option>)}</select></span></label> }
function RevenueShareModal({ onClose, onSave }: { onClose: () => void; onSave: () => void }) { return <div className="teacher-create-lesson__revenue-backdrop"><section className="teacher-create-lesson__revenue-modal" role="dialog" aria-modal="true" aria-labelledby="revenue-title"><header><h2 id="revenue-title">Add Revenue Shares</h2><button type="button" onClick={onClose}><X size={20} /></button></header><SelectField label="Select User" value="Type to search" options={['Type to search', 'John Doe', 'Jane Doe']} onChange={() => undefined} /><fieldset><legend>Commission Type</legend>{['Fixed Value', 'Fixed Percentage', 'Tiered Value', 'Tiered Percentage'].map((type, index) => <label key={type}><input type="radio" name="commission" defaultChecked={index === 0} /> {type}</label>)}</fieldset><Field label="Enter Value" value="0" onChange={() => undefined} /><button type="button" className="teacher-create-lesson__continue" onClick={onSave}>Save</button></section></div> }
