import { BookOpen, Check, ChevronDown, ChevronRight, FileQuestion, FileText, Filter, FolderOpen, Heart, MessageCircle, Plus, Search, Share2, Smile, X } from 'lucide-react'
import { useState } from 'react'
import '../../styles/pages/teacher-lesson-workspace.css'
import TeacherLessonAddModal, { type AddKind } from './TeacherLessonAddModal'
import { SubmissionsModal } from './TeacherAssignmentsPage'

type Tab = 'overview' | 'details' | 'timetable' | 'assignments' | 'students' | 'attendance' | 'resources' | 'activity' | 'questions'
const tabs: Array<[Tab, string]> = [['overview', 'Overview'], ['details', 'Lesson Details'], ['timetable', 'Timetable'], ['assignments', 'Assignments'], ['students', 'Students'], ['attendance', 'Attendance'], ['resources', 'Resources'], ['activity', 'Activity Log'], ['questions', 'Question Board']]
const people = ['Olivia Rhye', 'Phoenix Baker', 'Lana Steiner', 'Demi Wilkinson', 'Candice Wu', 'Natali Craig', 'Drew Cano', 'Orlando Diggs', 'Andi Lane', 'Kate Morrison']

export default function TeacherLessonWorkspace({ onClose, onStudentView }: { onClose: () => void; onStudentView?: () => void }) {
    const [activeTab, setActiveTab] = useState<Tab>('overview')
    const [menu, setMenu] = useState<'actions' | 'add' | null>(null)
    const [deactivateOpen, setDeactivateOpen] = useState(false)
    const [addKind, setAddKind] = useState<AddKind | null>(null)
    const [assignmentViewOpen, setAssignmentViewOpen] = useState(false)
    const closeMenu = () => setMenu(null)
    return <div className="teacher-lesson-workspace__backdrop" onMouseDown={event => event.target === event.currentTarget && onClose()}>
        <section className="teacher-lesson-workspace" role="dialog" aria-modal="true" aria-labelledby="teacher-lesson-title">
            <header className="teacher-lesson-workspace__topbar"><div className="teacher-lesson-workspace__crumb"><BookOpen size={16} /> Lessons <ChevronRight size={15} /><b id="teacher-lesson-title">Physics– Form 4</b></div><div className="teacher-lesson-workspace__actions"><div className="teacher-lesson-workspace__menu-wrap"><button type="button" aria-expanded={menu === 'actions'} onClick={() => setMenu(menu === 'actions' ? null : 'actions')}>Other Actions <ChevronDown size={15} /></button>{menu === 'actions' && <div className="teacher-lesson-workspace__menu"><button type="button" onClick={onStudentView}>Student View</button><button type="button" onClick={closeMenu}>Edit Details</button><button type="button" onClick={() => { closeMenu(); setDeactivateOpen(true) }}>Deactivate</button></div>}</div><div className="teacher-lesson-workspace__menu-wrap"><button type="button" aria-expanded={menu === 'add'} onClick={() => setMenu(menu === 'add' ? null : 'add')}><Plus size={15} /> Add</button>{menu === 'add' && <div className="teacher-lesson-workspace__menu"><button type="button" onClick={() => setAddKind('assignment')}><FileText size={14} /> Assignment</button><button type="button" onClick={() => setAddKind('exam')}><ClipboardIcon /> Exam</button><button type="button" onClick={() => setAddKind('quiz')}><FileQuestionIcon /> Quiz</button><button type="button" onClick={() => setAddKind('resource')}><FolderIcon /> Resources</button></div>}</div>{activeTab === 'overview' && <button className="is-primary" type="button">Start Teaching</button>}<button className="teacher-lesson-workspace__close" type="button" aria-label="Close" onClick={onClose}><X size={19} /></button></div></header>
            <div className="teacher-lesson-workspace__summary"><Summary title="Physics Form 4" detail="Date Created: 11 Jan 2025" /><Summary title="Tutor" detail="Jane Doe" /><Summary title="Duration" detail="10 Hrs" /><Summary title="No of Lessons" detail="10" /><Summary title="Curriculum" detail="CBC" /><Summary title="Grade" detail="Grade 6" /><Summary title="Status" detail="Ongoing" status /></div>
            <nav className="teacher-lesson-workspace__tabs">{tabs.map(([key, label]) => <button className={activeTab === key ? 'is-active' : ''} type="button" onClick={() => setActiveTab(key)} key={key}>{label}</button>)}</nav>
            <main className="teacher-lesson-workspace__body">{activeTab === 'overview' && <Overview />}{activeTab === 'details' && <Details />}{activeTab === 'timetable' && <Timetable />}{activeTab === 'assignments' && <Assignments onView={() => setAssignmentViewOpen(true)} />}{activeTab === 'students' && <Students />}{activeTab === 'attendance' && <Attendance />}{activeTab === 'resources' && <Resources />}{activeTab === 'activity' && <ActivityLog />}{activeTab === 'questions' && <Questions />}</main>
        </section>
        {deactivateOpen && <div className="teacher-lesson-workspace__confirm-backdrop"><section className="teacher-lesson-workspace__confirm" role="alertdialog" aria-modal="true" aria-labelledby="deactivate-lesson-title"><header><h2 id="deactivate-lesson-title">Deactivate Lesson</h2><button type="button" aria-label="Close" onClick={() => setDeactivateOpen(false)}><X size={19} /></button></header><p>Are you sure you want to deactivate this lesson?</p><label>Reason for deactivation<textarea placeholder="Enter a reason..." /></label><button className="is-danger" type="button" onClick={() => setDeactivateOpen(false)}>Deactivate Lesson</button></section></div>}
        {addKind && <TeacherLessonAddModal kind={addKind} onClose={() => { setAddKind(null); setMenu(null) }} />}
        {assignmentViewOpen && <SubmissionsModal elevated onClose={() => setAssignmentViewOpen(false)} />}
    </div>
}
function ClipboardIcon() { return <FileText size={14} /> }
function FileQuestionIcon() { return <FileQuestion size={14} /> }
function FolderIcon() { return <FolderOpen size={14} /> }
function Summary({ title, detail, status }: { title: string; detail: string; status?: boolean }) { return <div><small>{title}</small>{status ? <b className="teacher-lesson-workspace__status">{detail}</b> : <strong>{detail}</strong>}</div> }
function SearchBar({ placeholder = 'Search' }: { placeholder?: string }) { return <label className="teacher-lesson-workspace__search"><Search size={18} /><input placeholder={placeholder} /><Filter size={17} /></label> }
function CardTitle({ title }: { title: string }) { return <header className="teacher-lesson-workspace__section-title"><h2>{title}</h2><button type="button">Edit</button></header> }
function Overview() { return <><p className="teacher-lesson-workspace__eyebrow">Performance Overview</p><section className="teacher-lesson-workspace__performance"><span>Avg Grade <b>A- 90 Points</b></span><span>Attendance Rate <b>80%</b></span><span>Performance <b>High 87%</b><i /></span></section><section className="teacher-lesson-workspace__stats"><Stat label="Currently Enrolled Students" value="0" /><Stat label="Student Completed" value="0" /><Stat label="Total Resources" value="0" /></section><section className="teacher-lesson-workspace__overview-grid"><div className="teacher-lesson-workspace__chart"><h2>Class Attendance Trend</h2><div className="teacher-lesson-workspace__bars">{[28, 44, 75, 62, 47, 31, 83].map((height, index) => <span style={{ height: `${height}%` }} key={index} />)}</div><div className="teacher-lesson-workspace__chart-labels">{['12 Jan', '13 Jan', '14 Jan', '15 Jan', '16 Jan', '17 Jan', '18 Jan', '19 Jan'].map(day => <small key={day}>{day}</small>)}</div></div><div className="teacher-lesson-workspace__top-students"><h2>Top Students</h2><p>Top 3 student by performance</p><div className="teacher-lesson-workspace__donut" /><div className="teacher-lesson-workspace__legend"><span>● Jane Doe <b>94%</b></span><span>● Tim Otieno <b>85%</b></span><span>● Shem O <b>70%</b></span></div></div></section><ActivityFeed /></> }
function Stat({ label, value }: { label: string; value: string }) { return <div><BookOpen size={18} /><small>{label}</small><strong>{value}</strong></div> }
function ActivityFeed() { return <aside className="teacher-lesson-workspace__activity-feed"><h2>Activity Feed</h2><p><b>S</b> Sqooli <small>5 min ago</small><br />You submitted assignment #123456 successfully</p><p><b>J</b> John Kamau <small>5 min ago</small><br />Kindly help me answer this question</p></aside> }
function Details() { return <div className="teacher-lesson-workspace__narrow"><Info title="Basic Information" rows={['Lesson Title|Holiday Tuition Grade 6', 'Lesson Type|Tuition Program', 'Lesson Description|CBC', 'Curriculum|CBC', 'Grade Level|Grade 6', 'Subject|Grade 6', 'Program|Grade 6', 'Tutor|12 Jan 2026']} /><Info title="Learning Objectives" rows={['Learning objective one|', 'Learning objective two|', 'Learning objective three|']} /><Info title="Learning Requirement" text="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat." /><section className="teacher-lesson-workspace__card"><CardTitle title="Lesson Content" />{['Topic 1', 'Topic 2', 'Topic 3', 'Topic 4'].map((topic, i) => <Topic key={topic} title={topic} open={i === 0} />)}</section><Info title="Pricing" rows={['Rate Per Lesson|Holiday Tuition Grade 6', 'Sqooli Service Fee|Tuition Program', 'What you will receive|CBC', 'Additional Revenue Shares|YES']} /></div> }
function Info({ title, rows, text }: { title: string; rows?: string[]; text?: string }) { return <section className="teacher-lesson-workspace__card"><CardTitle title={title} />{rows?.map(row => { const [key, value] = row.split('|'); return <div className="teacher-lesson-workspace__info-row" key={key}><span>{key}</span><b>{value}</b></div> })}{text && <p className="teacher-lesson-workspace__copy">{text}</p>}</section> }
function Topic({ title, open }: { title: string; open?: boolean }) { return <article className="teacher-lesson-workspace__topic"><header><b>{title}</b><small>4 Lectures · 50 min</small><ChevronDown size={16} /></header>{open && <div><strong>What you will learn</strong><p><Check size={14} /> Gain an immersive understanding of the practices and skills needed to succeed in an entry-level project management role</p><p><Check size={14} /> Gain an immersive understanding of the practices and skills needed to succeed in an entry-level project management role</p>{['Video Introduction', 'Video Introduction', 'What you will learn in this lesson', 'Notes Example', 'Assignment Example'].map(item => <span key={item}><FileText size={14} />{item}<em>3.08 min</em></span>)}</div>}</article> }
function Timetable() { return <div><h2 className="teacher-lesson-workspace__page-title">Timetable</h2><div className="teacher-lesson-workspace__calendar-layout"><aside className="teacher-lesson-workspace__mini-calendar"><strong>February 2023</strong><div className="teacher-lesson-workspace__calendar-days">{Array.from({ length: 35 }, (_, i) => <span className={i === 16 ? 'is-today' : ''} key={i}>{(i + 30) % 31 + 1}</span>)}</div><h3>Key</h3><p><i className="lesson" /> Lesson</p><p><i className="exam" /> Exam</p><p><i className="event" /> School Event</p></aside><div className="teacher-lesson-workspace__month"><header><h2>February 2023</h2><button type="button"><Filter size={15} /> Add filters</button><button type="button">Month <ChevronDown size={15} /></button></header><div className="teacher-lesson-workspace__month-grid">{['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'].map(day => <b key={day}>{day}</b>)}{Array.from({ length: 28 }, (_, i) => <div key={i}><small>{i + 1}</small>{[0, 2, 13].includes(i) && <span>Jane Doe</span>}</div>)}</div></div></div></div> }
function Assignments({ onView }: { onView: () => void }) { return <div className="teacher-lesson-workspace__table-layout"><aside className="teacher-lesson-workspace__filters"><b className="is-active">Upcoming</b><b>Ongoing</b><b>Completed</b></aside><Table headers={['Assignment Name', 'Start Date', 'No of Students', '']} rows={Array.from({ length: 10 }, (_, i) => ['Test 1', i ? '12 Jan 2026' : '3 days', '24', 'View'])} onView={onView} /></div> }
function Students() { return <div><SearchBar placeholder="Search students" /><div className="teacher-lesson-workspace__subtabs"><button className="is-active" type="button">Active</button><button type="button">Inactive</button></div><Table headers={['Date Added', 'Name', 'Performance Rate (%)', 'Attendance Rate (%)', '']} rows={people.map(name => ['24 Jan 2025 11.00 AM', name, '50', '50', 'View'])} /></div> }
function Attendance() { return <div><SearchBar /><div className="teacher-lesson-workspace__attendance-heading"><b>01 Mar 2025 - 7 Mar 2025</b><span>2025⌄  Jan  Feb  <strong>Mar</strong>  Apr  May  Jun  Jul  Aug  Sep</span></div><div className="teacher-lesson-workspace__attendance-table"><div />{Array.from({ length: 12 }, (_, i) => <b key={i}>{i + 1}<small>Mar</small></b>)}{people.slice(0, 7).map(name => <div className="attendance-row" key={name}><span>{name}</span>{Array.from({ length: 12 }, (_, i) => <i className={i === 3 ? 'absent' : i > 9 ? 'empty' : ''} key={i} />)}</div>)}</div></div> }
function Resources() { return <div><SearchBar /><div className="teacher-lesson-workspace__subtabs">{['Assignments', 'Quizzes', 'Exams', 'Books', 'Notes', 'Videos'].map((item, i) => <button className={i === 0 ? 'is-active' : ''} type="button" key={item}>{item}</button>)}</div><Table headers={['Assignment Name', 'Program', 'Grade', 'Created By', '']} rows={['Basketball', 'Tennis', 'Arts & Craft', 'Programming', 'Netball', '50', '50', '50'].map(item => [item, item, item, 'Olivia Rhye', 'View'])} /></div> }
function ActivityLog() { return <section className="teacher-lesson-workspace__card teacher-lesson-workspace__timeline"><SearchBar />{['John Juma Downloaded Report #123456', 'John Juma Downloaded Report #123456', 'Peter Okumu send a message', 'Peter Okumu send a message', 'Peter Okumu send a message'].map((item, i) => <p key={i}><b>{i === 0 ? 'S' : 'J'}</b><span>{item}<small>22 Jan 2024 at 9:34:12 PM</small></span></p>)}</section> }
function Questions() { return <div className="teacher-lesson-workspace__question-layout"><div><SearchBar placeholder="Atom" />{[1, 2, 3, 4].map(item => <article className="teacher-lesson-workspace__question" key={item}><strong>Lucy <small>Student</small></strong><time>3 days ago</time><h3>What is an atom?</h3><b>Chemistry</b><p><MessageCircle size={15} /> 20 <Heart size={15} /> 20 <Smile size={15} /> 20 <Share2 size={15} /> 20</p><button type="button">View</button></article>)}</div><aside className="teacher-lesson-workspace__recent"><h2>Recent Posts</h2><p>Lucy · Parent</p><h3>What is an atom?</h3><b>Chemistry</b><p><MessageCircle size={15} /> 20 <Heart size={15} /> 20</p><hr /><p>Lucy · Parent</p><h3>What is an atom?</h3></aside></div> }
function Table({ headers, rows, onView }: { headers: string[]; rows: string[][]; onView?: () => void }) { return <div className="teacher-lesson-workspace__table-wrap"><table><thead><tr>{headers.map(header => <th key={header}>{header}</th>)}</tr></thead><tbody>{rows.map((row, i) => <tr key={i}>{row.map((cell, j) => <td key={j}>{j === row.length - 1 && cell === 'View' ? <button type="button" onClick={onView}>View</button> : cell}</td>)}</tr>)}</tbody><tfoot><tr><td colSpan={headers.length}>Page <b>1</b> of 10 <span>Previous  Next</span></td></tr></tfoot></table></div> }
