import { Filter, MessageCircle, School, Search, Send, X } from 'lucide-react'
import { useState } from 'react'
import TeacherDashboardLayout from './TeacherDashboardLayout'
import '../../styles/pages/teacher-communication.css'

const conversations = ['Janet Nyambura', 'Janet Nyambura', 'Janet Nyambura', 'Janet Nyambura', 'Janet Nyambura', 'Janet Nyambura', 'Janet Nyambura', 'Janet Nyambura']
export default function TeacherCommunicationPage() {
	const [selected, setSelected] = useState<string | null>(null); const [chatOpen, setChatOpen] = useState(false); const [message, setMessage] = useState(''); const [query, setQuery] = useState('')
	const visible = conversations.filter(name => name.toLowerCase().includes(query.toLowerCase()))
	return <TeacherDashboardLayout><section className="teacher-communication-page"><a className="teacher-communication-page__back" href="/teacher/dashboard">← Back to Dashboard</a><div className="teacher-communication-page__layout"><TeacherCommunicationRail /><main><header><div><h1>Communication Hub</h1><p>View and manage communication with other users</p></div><button type="button" onClick={() => setChatOpen(true)}>Start Chat</button></header><div className="teacher-communication-page__messaging"><section className="teacher-communication-page__inbox"><label><Search size={18} /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search" /><Filter size={16} /></label>{visible.map((name, index) => <button className={selected === name + index ? 'is-selected' : ''} type="button" key={name + index} onClick={() => setSelected(name + index)}><span className="teacher-communication-page__avatar">{index < 3 ? '' : 'J'}</span><span><b>{name}</b><small>Hello, I need some help with....</small></span><em>08:39</em>{index < 3 && <i>2</i>}</button>)}</section><section className="teacher-communication-page__thread">{selected ? <><div className="teacher-communication-page__thread-head"><b>{selected.replace(/\d+$/, '')}</b><small>Thursday 11:40am</small></div><div className="teacher-communication-page__messages"><p className="is-them">Good timing — was just looking at this.</p><p className="is-me">Awesome! Thanks.</p><p className="is-them">Can you please review the latest design when you can?</p><p className="is-me">Sure thing, I’ll have a look today.</p></div></> : <div className="teacher-communication-page__empty"><MessageCircle size={54} /><h2>Start a conversation</h2><p>Select a conversation or start a new chat.</p></div>}<form onSubmit={event => { event.preventDefault(); setMessage('') }}><input value={message} onChange={event => setMessage(event.target.value)} placeholder="Type Message" /><button type="submit" aria-label="Send message"><Send size={17} /></button></form></section></div></main></div></section>{chatOpen && <StartChatModal onClose={() => setChatOpen(false)} onStart={() => { setChatOpen(false); setSelected('Janet Nyambura0') }} />}</TeacherDashboardLayout>
}
function TeacherCommunicationRail() { return <aside className="teacher-communication-page__rail"><div className="teacher-communication-page__school-mark"><School size={25} /></div><h2>Mathematic Excellence<br />Academy</h2><span>Online School</span><p>Contact Information</p><strong>+254712 345 678</strong><strong>mathematicexcel@gmail.com</strong><button type="button">Switch Account</button></aside> }
function StartChatModal({ onClose, onStart }: { onClose: () => void; onStart: () => void }) { return <div className="teacher-chat-modal__backdrop" onMouseDown={event => event.target === event.currentTarget && onClose()}><section className="teacher-chat-modal" role="dialog" aria-modal="true"><header><h2>Start Chat</h2><button type="button" aria-label="Close" onClick={onClose}><X size={20} /></button></header><label>Phone Number<span><b className="teacher-chat-modal__country">KE</b><em>⌄</em><i>+254</i><input inputMode="numeric" placeholder="Phone number" /></span></label><button className="teacher-chat-modal__start" type="button" onClick={onStart}>Start Chat</button></section></div> }
