import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../../globals.css";

import { Roboto } from "next/font/google";
import AuthWrapper from "@/app/components/auth/AuthWrapper";
import TopMenu from "@/app/components/menu/topmenu";
import Sidebar from "@/app/components/menu/sidebar";
import { PermissionProvider } from "@/app/lib/auth/PermissionContext";
import AuthInitializer from "@/app/components/auth/AuthInitializer";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Sqooli",
  description: "Generated by Swiftcode",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

        <div className="flex h-screen bg-gray-100 relative">
          {/* Toggle button - always visible, positioned independently */}
          <Sidebar />

          {/* Main Content */}
          <div className="flex-1 flex flex-col overflow-hidden">
            {/* Header */}
            <TopMenu />

            {/* Page Content */}
            <main className="flex-1 overflow-auto bg-white relative h-screen">
              <AuthWrapper>     
                <AuthInitializer>
                        <PermissionProvider>{children}</PermissionProvider>
                        </AuthInitializer>

                </AuthWrapper>
            </main>
          </div>
        </div>

  );
}
