import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Sidebar from "../components/menu/sidebar";
import TopMenu from "../components/menu/topmenu";
import AuthWrapper from "../components/auth/AuthWrapper";

import { Roboto } from "next/font/google";
import GlobalSpinner from "@/components/GlobalSpinner";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Sqooli",
  description: "Generated by Swiftcode",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <div className="flex h-screen bg-gray-100 relative">
          {/* Toggle button - always visible, positioned independently */}

          {/* Main Content */}
          <div className="flex-1 flex flex-col overflow-hidden">
            {/* Header */}
            {/* <TopMenu /> */}

            {/* Page Content */}
            <main className="flex-1 overflow-auto bg-white relative h-screen">
              <GlobalSpinner/>
            {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
