import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import StudentTopmenu from "../components/menu/studentTopmenu";
import LiveTopMenu from "../components/menu/liveTopMenu";
import AuthWrapper from "../components/auth/AuthWrapper";
import GlobalErrorHandler from "@/lib/GlobalErrorHandler";
import MyToaster from "../components/general/Toast/MyToaster";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Sqooli",
  description: "Generated by Swiftcode",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex h-screen bg-gray-100 relative">
          {/* Main Content */}
          <div className="flex-1 flex flex-col overflow-hidden">
            {/* Header */}
            <MyToaster/>
<GlobalErrorHandler />
            <LiveTopMenu />
            {/* Page Content */}
            <main className="flex-1 overflow-auto bg-white relative h-screen">
              <AuthWrapper>{children}</AuthWrapper>
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
